Feature/53909 CRM Main browser
FJala-Tr2020/front-end-e3 pull request #1
Opened 2021-07-07 21:47 UTC by SofieTorch

2021-07-08 02:51 UTC, marcelo-yourday submitted a review, later dismissed

2021-07-08 02:51 UTC, marcelo-yourday commented on src/components/MainNavBar.html
> +        <a class="nav-link" href="#">Leads<span class="sr-only">(current)</span></a>
@SofieTorch this implementation is for the PBI 53911, please next time try to create a pull request for each PBI.

2021-07-08 02:51 UTC, marcelo-yourday commented on src/components/MainNavBar.html
> +      <a class="nav-link" href="#">Versión</a>
This implementation is for PBI 53910, you should create a pull request for each separated PBI. Nevertheless, it is not needed to create a new pull request since you already have the implementation.

2021-07-08 02:51 UTC, marcelo-yourday commented on src/components/MainNavBar.html
> +        <a class="nav-link" href="#">Leads<span class="sr-only">(current)</span></a>
What happens if sometime in the future we change the menu item Leads?, instead of having this as a hard-coded string, we can have some property in the View Model. A more scalable way to do this can be having components for each menu item, nevertheless, it is enough to move this string to view the model, but maybe we can create an abstraction for the menu.

2021-07-08 02:51 UTC, marcelo-yourday commented on src/components/MainNavBar.html
> +      <a class="nav-link" href="#">Versión</a>
Similar comment for the Version option, we need to have an abstraction for the menu items.

2021-07-08 02:51 UTC, marcelo-yourday commented on src/components/MainNavBar.ts
> +
Instead of having an empty class, we will have some abstractions for Leads and Version.

2021-07-08 02:51 UTC, marcelo-yourday commented on src/index.html
> +  <leads-view></leads-view>
As described in PBI 53911, the leads view should only be shown when clicking on the Leads menu item.

2021-07-20 01:14 UTC, eencinasq requested changes

2021-07-20 01:14 UTC, eencinasq commented on src/components/NavBar.html
> +      <li class="nav-item">
IMO this part could be a stateless component, could we updated it, please?
e.g
`
<nav-item params="onClick: action, label: label"></nav-item>
`

2021-07-20 01:14 UTC, eencinasq commented on src/components/NavBar.ts
> +class MainNavBar {
Change MainNavBar to NavBard, please.

2021-07-20 01:14 UTC, eencinasq commented on src/index.html
> +  <main-navbar></main-navbar>
IMO this part could be a stateless component, could we updated it, please?
e.g
`
<navbar params="leftItems: leftData, rightItems: rightData"></navbar>
`

2021-07-22 00:53 UTC, merged